# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.19.3
fabric_kotlin_version=1.13.6+kotlin.2.2.20
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.3.5+1.21.10
maven_group=nl.piguy.allaybottle
archives_base_name=allaybottle

# Dependencies
fabric_version=0.138.4+1.21.10